name = "saikat"
license = "MIT"
licenselink = "https://github.com/Somrat37/somrat/blob/master/LICENSE"
description = "Portfolio Template"
homepage = "https://ypath-hoover-saikat.netlify.app/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'dark', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.60.0"

[author]
  name = "saikat"
  homepage = "https://ypath-hoover-saikat.netlify.app/"